### ISSUE TITLE
Sitebot/modules/glftpd : skip "group/user/0 bytes" in stats

### ISSUE THREAD

**Issue by MrCodeFr** [pzs-ng/pzs-ng#10]
It should be nice to be able to configure "group/user/0 bytes" to exclude in stats commands.

I mean, when sitebot call $binary(STATS) in cmd_stats, the exec should use, if configured, theses flags of stats :

```
      -e <user> exclude user from stats
      -g <group> exclude group from stats
      -0 [omit users/groups with zero bytes]
```

**Comment by Skeddie** [comment]
Implemented since 016700edc32c9b176dda074dcb67be2611cd07ab.
