### ISSUE TITLE
Delete incomplete directories?

### ISSUE THREAD

**Issue by scriptzteam** [pzs-ng/pzs-ng#14]
How can i delete incomplete directories? Not only symlink but whole dir?

**Comment by Skeddie** [comment]
That's not really a pzs-ng issue now is it?
Via GUI:
- follow the symlink
- go to the parent dir
- delete or wipe the dir

Scripted:
- get path link is pointing to
- wipe or delete dir

Some clients have the option to delete the dir/file a symlink points to.
