### ISSUE TITLE
ngBot.tcl login.log regex pattern error

### ISSUE THREAD

**Issue by iknowmarkers** [pzs-ng/pzs-ng#25]
commit https://github.com/pzs-ng/pzs-ng/commit/2d13312777283157d770028c20dadc595b705a4a#diff-080eb1de0a039e6fcd9e6a9e3f26a6a7R514 breaks detection of certain login.log lines when using -X (never log ip's) is used with glftpd. "user: disabled@disabled (disabled): Deleted." is how the line appears in the logfile.

**Comment by Skeddie** [comment]
Thanks for reporting, fixed in referenced commit.
