### ISSUE TITLE
psxc-imdb plot/cast & bom

### ISSUE THREAD

**Issue by silv3rr** [pzs-ng/pzs-ng#28]
https://github.com/pzs-ng/pzs-ng/blob/a8a5fa2396f3015290043d03d2dd12d75253bb52/scripts/psxc-imdb/main/psxc-imdb.sh#L550

Seems there are 2 issues with "Plot":
- as "*" char is not escaped it lists files in current dir in $PLOT
- no linebreaks on long lines / handling multiple plot lines

Possible fix:

```
PLOT="Plot: "$(sed -n '/^ Plot Summary$/,/^ \* Plot Summary$/{//d;p;}' "$TMPFILE" | sed s/\"/$QUOTECHAR/g | sed 's/^\ *//g' | tr -s ' ' | sed "s/ *$//" | fold -s -w 275 | sed ':a;N;$!ba;s/\n/\\\\n/g')""
```

This removes " * Plot Summary" and uses fold/sed to break lines

**Comment by silv3rr** [comment]
Addition:

- it's better to set fold -w to a lower value like **275**, specially if you're using blowfish encryption (= longer lines)
- also, to remove the extra newlines from dotimdb files change:

https://github.com/pzs-ng/pzs-ng/blob/a8a5fa2396f3015290043d03d2dd12d75253bb52/scripts/psxc-imdb/main/psxc-imdb.sh#L898

to:

```
echo "$PLOT" | sed 's/\\\\n//g' | fold -s -w $IMDBWIDTH >> "$IMDBLNK"
```

**Comment by i137** [comment]
Thanks @silv3rr, that fixes the unwanted file listing. Make a pull request?

**Comment by silv3rr** [comment]
@i137 there will be but i have a few more local changes to commit first e.g. to remove "Written by":

https://github.com/pzs-ng/pzs-ng/blob/a8a5fa2396f3015290043d03d2dd12d75253bb52/scripts/psxc-imdb/main/psxc-imdb.sh#L550
change:
```bash
PLOT="Plot: "$(sed -n '/^ Plot Summary$/,/^ \* Plot Summary$/{//d;p;}' "$TMPFILE" | sed 's/Written by .*$//' | sed s/\"/$QUOTECHAR/g | sed 's/^\ *//g' | tr -s ' ' | sed "s/ *$//" | fold -s -w 275 | sed ':a;N;$!ba;s/\n/\\\\n/g')""
```

Also testing using boxofficemojo for "screens" but needs better matching imdb tt <-> title on BOM. Plus few other small tidbits (import fold and add width as variable in conf, replace \\\\n by $NEWLINE etc).

**Comment by silv3rr** [comment]
More plot/cast fixes: https://git.io/fjw4p

No BOM integration yet...  if anyone else wants to try:
http://www.boxofficemojo.com/search/?q=${IMDBTILE}&sort=date&showpage=1&p=.htm

It seems that if there's a match BOM highlights the title in yellow ( `<tr bgcolor="#FFFF99">` ), but often there isn't (and there's multiple results)..

**Comment by silv3rr** [comment]
Done:
https://github.com/silv3rr/pzs-ng/tree/master/scripts/psxc-imdb & PR #39
