### ISSUE TITLE
small fix for incomplete-list.sh

### ISSUE THREAD

**Issue by silv3rr** [pzs-ng/pzs-ng#31]
https://github.com/pzs-ng/pzs-ng/blob/a8a5fa2396f3015290043d03d2dd12d75253bb52/sitebot/extra/incomplete-list.sh#L68
```bash
comp="`ls -1 /$glroot/$result/ | grep "$releaseComplete"`"
```

**Comment by Skeddie** [comment]
Thanks for your suggestion but in combination with the referenced issue, another solution was chosen.
