### ISSUE TITLE
incomplete-list.sh does not show any incompletes

### ISSUE THREAD

**Issue by milesbenson** [pzs-ng/pzs-ng#32]
... even if there are some. When i run incomplete-list.sh from commandline, then there are incompletes shown. What am i doing wrong?

./incomplete-list.sh works fine, chroot /glftpd /bin/incomplete-list.sh does not show any incompletes either. I guess it's something in the configuration as i dont have glftpd in /glftpd

glroot=/mnt/sda
cleanup=$glroot/bin/cleanup
sections="
section1:/site/section/
"
seems to be wrong?

**Comment by silv3rr** [comment]
#31  ?

**Comment by milesbenson** [comment]
No, unfortunately not

**Comment by Skeddie** [comment]
See latest commit where I removed the chroot() call and thus the need for +s on the cleanup bin. This should fix this issue.
