### ISSUE TITLE
missing COMPLETE tag in glftpd.log

### ISSUE THREAD

**Issue by donmagic1** [pzs-ng/pzs-ng#37]
Here is log of glftpd.log, it sometimes missing Complete tag, but when you enter in dir, it says completed.

`Sat Jun  1 08:28:05 2019 NEWDIR: "/site/TV-X264/Web.of.Lies.S05E06.1080p.WEB.x264-57CHAN" "deleted" "iND" "deleted"
Sat Jun  1 08:28:05 2019 SFV_RAR: "/site/TV-X264/Web.of.Lies.S05E06.1080p.WEB.x264-57CHAN" {Web.of.Lies.S05E06.1080p.WEB.x264-57CHAN} {22} {deleted} {iND} {web.of.lies.s05e06.1080p.web.x264.sfv} "deleted"
Sat Jun  1 08:28:08 2019 UPDATE_RAR: "/site/TV-X264/Web.of.Lies.S05E06.1080p.WEB.x264-57CHAN" {deleted} {iND} {22} {36303} {2098.1} {web.of.lies.s05e06.1080p.web.x264.r16} {Web.of.Lies.S05E06.1080p.WEB.x264-57CHAN} "deleted" {0} {1m4s}
Sat Jun  1 08:28:12 2019 RACE_RAR: "/site/TV-X264/Web.of.Lies.S05E06.1080p.WEB.x264-57CHAN" {deleted} {iND} {{deleted} {iND}} {Web.of.Lies.S05E06.1080p.WEB.x264-57CHAN} {13881} {web.of.lies.s05e06.1080p.web.x264.r01} {6s} {9.1} {2} {1} {2} {22} {20} "deleted" {{deleted} {iND}} {0} {1m22s}
Sat Jun  1 08:28:17 2019 NEWLEADER_RAR: "/site/TV-X264/Web.of.Lies.S05E06.1080p.WEB.x264-57CHAN" {deleted} {iND} {11341} {11s} {4} {18.2} {381} {Web.of.Lies.S05E06.1080p.WEB.x264-57CHAN} {web.of.lies.s05e06.1080p.web.x264.rar} {2} {1} {22} {18} {deleted} {iND} {286.1} {3} {75.0} {12365} {iND} {381.5} {4} {100.0} {18350} "deleted" {{deleted} {iND}} {0} {55s}
Sat Jun  1 08:28:22 2019 RACE_RAR: "/site/TV-X264/Web.of.Lies.S05E06.1080p.WEB.x264-57CHAN" {deleted} {iND} {{deleted} {iND} {deleted} {iND}} {Web.of.Lies.S05E06.1080p.WEB.x264-57CHAN} {18938} {web.of.lies.s05e06.1080p.web.x264.r07} {16s} {40.9} {3} {1} {9} {22} {13} "Echo Hello World" {{deleted} {iND} {deleted} {iND}} {0} {28s}
Sat Jun  1 08:28:24 2019 RACE_RAR: "/site/TV-X264/Web.of.Lies.S05E06.1080p.WEB.x264-57CHAN" {deleted} {iND} {{deleted} {iND} {deleted} {iND} {deleted} {iND}} {Web.of.Lies.S05E06.1080p.WEB.x264-57CHAN} {7916} {web.of.lies.s05e06.1080p.web.x264.r08} {17s} {45.5} {4} {1} {10} {22} {12} "deleted" {{deleted} {iND} {deleted} {iND} {deleted} {iND}} {0} {27s}
Sat Jun  1 08:28:25 2019 RACE_RAR: "/site/TV-X264/Web.of.Lies.S05E06.1080p.WEB.x264-57CHAN" {deleted} {iND} {{deleted} {iND} {deleted} {iND} {deleted} {iND} {deleted} {iND}} {Web.of.Lies.S05E06.1080p.WEB.x264-57CHAN} {11830} {web.of.lies.s05e06.1080p.web.x264.r05} {19s} {50.0} {5} {1} {11} {22} {11} "deleted" {{deleted} {iND} {deleted} {iND} {deleted} {iND} {deleted} {iND}} {0} {25s}
Sat Jun  1 08:28:25 2019 HALFWAY_RACE_RAR: "/site/TV-X264/Web.of.Lies.S05E06.1080p.WEB.x264-57CHAN" {Web.of.Lies.S05E06.1080p.WEB.x264-57CHAN} {deleted} {iND} {381.5} {4} {36.4} {11073} {iND} {1049.0} {11} {100.0} {14673} {1049} {11} {50.0} {56538} {7337} {11} {web.of.lies.s05e06.1080p.web.x264.r05} {5} {1} {deleted} {iND} {22} {{deleted} {iND} {deleted} {iND} {deleted} {iND} {deleted} {iND}} {0} {25s}
Sat Jun  1 08:28:31 2019 NEWDIR: "/site/TV-X264/Web.of.Lies.S05E06.1080p.WEB.x264-57CHAN/Sample" "deleted" "iND" "deleted"
Sat Jun  1 08:28:43 2019 BAD_FILE_CRC: "/site/TV-X264/Web.of.Lies.S05E06.1080p.WEB.x264-57CHAN" {Web.of.Lies.S05E06.1080p.WEB.x264-57CHAN} {deleted} {iND} {web.of.lies.s05e06.1080p.web.x264.r15}
Sat Jun  1 08:28:47 2019 BAD_FILE_CRC: "/site/TV-X264/Web.of.Lies.S05E06.1080p.WEB.x264-57CHAN" {Web.of.Lies.S05E06.1080p.WEB.x264-57CHAN} {deleted} {iND} {web.of.lies.s05e06.1080p.web.x264.r11}
Sat Jun  1 08:28:48 2019 BAD_FILE_CRC: "/site/TV-X264/Web.of.Lies.S05E06.1080p.WEB.x264-57CHAN" {Web.of.Lies.S05E06.1080p.WEB.x264-57CHAN} {deleted} {iND} {web.of.lies.s05e06.1080p.web.x264.r19}
Sat Jun  1 08:28:48 2019 BAD_FILE_CRC: "/site/TV-X264/Web.of.Lies.S05E06.1080p.WEB.x264-57CHAN" {Web.of.Lies.S05E06.1080p.WEB.x264-57CHAN} {deleted} {iND} {web.of.lies.s05e06.1080p.web.x264.r13}
Sat Jun  1 08:28:50 2019 BAD_FILE_CRC: "/site/TV-X264/Web.of.Lies.S05E06.1080p.WEB.x264-57CHAN" {Web.of.Lies.S05E06.1080p.WEB.x264-57CHAN} {deleted} {iND} {web.of.lies.s05e06.1080p.web.x264.r19}
Sat Jun  1 08:28:52 2019 BAD_FILE_CRC: "/site/TV-X264/Web.of.Lies.S05E06.1080p.WEB.x264-57CHAN" {Web.of.Lies.S05E06.1080p.WEB.x264-57CHAN} {deleted} {iND} {web.of.lies.s05e06.1080p.web.x264.r09}
Sat Jun  1 08:28:53 2019 BAD_FILE_CRC: "/site/TV-X264/Web.of.Lies.S05E06.1080p.WEB.x264-57CHAN" {Web.of.Lies.S05E06.1080p.WEB.x264-57CHAN} {deleted} {iND} {web.of.lies.s05e06.1080p.web.x264.r06}
Sat Jun  1 08:28:57 2019 BAD_FILE_CRC: "/site/TV-X264/Web.of.Lies.S05E06.1080p.WEB.x264-57CHAN" {Web.of.Lies.S05E06.1080p.WEB.x264-57CHAN} {deleted} {iND} {web.of.lies.s05e06.1080p.web.x264.r06}
Sat Jun  1 08:28:59 2019 BAD_FILE_CRC: "/site/TV-X264/Web.of.Lies.S05E06.1080p.WEB.x264-57CHAN" {Web.of.Lies.S05E06.1080p.WEB.x264-57CHAN} {deleted} {iND} {web.of.lies.s05e06.1080p.web.x264.r11}
Sat Jun  1 08:28:59 2019 RACE_RAR: "/site/TV-X264/Web.of.Lies.S05E06.1080p.WEB.x264-57CHAN" {deleted} {iND} {{deleted} {iND} {deleted} {iND} {deleted} {iND} {deleted} {iND} {deleted} {iND}} {Web.of.Lies.S05E06.1080p.WEB.x264-57CHAN} {197117} {web.of.lies.s05e06.1080p.web.x264.r13} {54s} {72.7} {6} {1} {16} {22} {6} "deleted" {{deleted} {iND} {deleted} {iND} {deleted} {iND} {deleted} {iND} {deleted} {iND}} {0} {34s}
Sat Jun  1 08:29:00 2019 BAD_FILE_CRC: "/site/TV-X264/Web.of.Lies.S05E06.1080p.WEB.x264-57CHAN" {Web.of.Lies.S05E06.1080p.WEB.x264-57CHAN} {deleted} {iND} {web.of.lies.s05e06.1080p.web.x264.r18}
Sat Jun  1 08:29:21 2019 BAD_FILE_CRC: "/site/TV-X264/Web.of.Lies.S05E06.1080p.WEB.x264-57CHAN" {Web.of.Lies.S05E06.1080p.WEB.x264-57CHAN} {deleted} {iND} {web.of.lies.s05e06.1080p.web.x264.r09}
Sat Jun  1 08:29:24 2019 BAD_FILE_CRC: "/site/TV-X264/Web.of.Lies.S05E06.1080p.WEB.x264-57CHAN" {Web.of.Lies.S05E06.1080p.WEB.x264-57CHAN} {deleted} {iND} {web.of.lies.s05e06.1080p.web.x264.r11}
Sat Jun  1 08:29:26 2019 BAD_FILE_CRC: "/site/TV-X264/Web.of.Lies.S05E06.1080p.WEB.x264-57CHAN" {Web.of.Lies.S05E06.1080p.WEB.x264-57CHAN} {Zotacion} {iND} {web.of.lies.s05e06.1080p.web.x264.r09}
Sat Jun  1 08:29:30 2019 RACE_RAR: "/site/TV-X264/Web.of.Lies.S05E06.1080p.WEB.x264-57CHAN" {deleted} {iND} {{deleted} {iND} {deleted} {iND} {deleted} {iND} {deleted} {iND} {deleted} {iND} {deleted} {iND}} {Web.of.Lies.S05E06.1080p.WEB.x264-57CHAN} {31387} {web.of.lies.s05e06.1080p.web.x264.r09} {1m24s} {90.9} {7} {1} {20} {22} {2} "who" {{deleted} {iND} {deleted} {iND} {deleted} {iND} {deleted} {iND} {deleted} {iND} {deleted} {iND}} {0} {26s}
Sat Jun  1 08:29:49 2019 BAD_FILE_CRC: "/site/TV-X264/Web.of.Lies.S05E06.1080p.WEB.x264-57CHAN" {Web.of.Lies.S05E06.1080p.WEB.x264-57CHAN} {deleted} {iND} {web.of.lies.s05e06.1080p.web.x264.r11}
Sat Jun  1 08:30:11 2019 BAD_FILE_DUPERELEASE: "/site/TV-X264/Web.of.Lies.S05E06.1080p.WEB.x264-57CHAN" {Web.of.Lies.S05E06.1080p.WEB.x264-57CHAN} {deleted} {iND} {web.of.lies.s05e06.1080p.web.x264.r11}
Sat Jun  1 08:30:11 2019 BAD_FILE_DUPERELEASE: "/site/TV-X264/Web.of.Lies.S05E06.1080p.WEB.x264-57CHAN" {Web.of.Lies.S05E06.1080p.WEB.x264-57CHAN} {deleted} {iND} {web.of.lies.s05e06.1080p.web.x264.r11}
Sat Jun  1 08:30:17 2019 BAD_FILE_DUPERELEASE: "/site/TV-X264/Web.of.Lies.S05E06.1080p.WEB.x264-57CHAN" {Web.of.Lies.S05E06.1080p.WEB.x264-57CHAN} {deleted} {iND} {web.of.lies.s05e06.1080p.web.x264.r03}
Sat Jun  1 08:30:17 2019 BAD_FILE_DUPERELEASE: "/site/TV-X264/Web.of.Lies.S05E06.1080p.WEB.x264-57CHAN" {Web.of.Lies.S05E06.1080p.WEB.x264-57CHAN} {deleted} {iND} {web.of.lies.s05e06.1080p.web.x264.r03}`

**Comment by Termin8or666** [comment]
I can confirm the same on tv shows,
announces HALF but never complete.. my guess is that half to complete is within seconds on 1gbit-10gbit connections

another example is that if you have a sorting script announce the sorting, if the sorting is moving stuff to another drive it announces everything BUT if its sorting to the same drive as the unsorted folder the move is instant and most of the moves does not reach the announce.

hopefully this info trigges some ideas for a fix :)

**Comment by maxpayneovh** [comment]
its botnuke related issue, i fixed botnuke and no more announce stucks.
