### ISSUE TITLE
announce for tvmaze rating?

### ISSUE THREAD

**Issue by terra-dude** [pzs-ng/pzs-ng#41]
Possible to update TV maze.tcl vars, 
so it announce the tv maze ratings to ?

rating |  
-- | --
average | 6.3

**Comment by teqnodude** [comment]
Below this line
`set ${np}::zeroconvert(%tvmaze_episode_title)             "N/A"`

Insert
`set ${np}::zeroconvert(%tvmaze_show_rating)               "N/A"`

Edit this line `set variables(TVMAZE-MSGFULL)`

And insert this `%tvmaze_show_rating`

Edit this section `set output_order [list show_name`

And insert this `show_rating`

Look for `return [array get info]`

And insert this right above it

```
# average rating
regexp {\"rating\":\{\"average\":([0-9].[0-9]|[0-9][0-9].[0-9])} $data -> show_rating
if {[info exists show_rating]} {
        set info(show_rating) $show_rating
}
```

Now edit the theme file and use this cookie `%tvmaze_show_rating`

Voila, Enjoy!

**Comment by terra-dude** [comment]
yeah nice work teq... they can implant this now.

**Comment by Skeddie** [comment]
Added in latest commit, thanks for your effort.
