### ISSUE TITLE
ssl updated for plugin tvmaze

### ISSUE THREAD

**Issue by PatriotM** [pzs-ng/pzs-ng#43]
if the tvmaze plugin would get an ssl update it would be great

https://www.tvmaze.com/api

**Comment by teqnodude** [comment]
I just did this and it seem to work just fine, at least with !tv trigger

Change line 384 from http:// to https://
`set data [GetFromApi "http://api.tvmaze.com/singlesearch/shows?embed%5b%5d=previousepisode&embed%5b%5d=nextepisode&q=" $show]`

To

`set data [GetFromApi "https://api.tvmaze.com/singlesearch/shows?embed%5b%5d=previousepisode&embed%5b%5d=nextepisode&q=" $show]`

Change line 488 from http:// to https://
`set data [GetFromApi "http://api.tvmaze.com/shows/${info(show_id)}/episodebynumber?season=${season}&number=${epnumber}" ""]`

To

`set data [GetFromApi "https://api.tvmaze.com/shows/${info(show_id)}/episodebynumber?season=${season}&number=${epnumber}" ""]`

Insert above line 523 
`if {[string length [info commands ::http::quoteString]]} {`

with new line 

`http::register https 443 tls::socket`

Insert below line 163
`if {[catch {package require http}]} {
		${ns}::Error "\"http\" package not found, unloading script."
		return -code -1
}`

with

```
if {[catch {package require tls}]} {
		${ns}::Error "\"tls\" package not found, unloading script."
		return -code -1
}

```

I am no expert in Tcl so I may have missed something but I don't think I have.

**Comment by terra-dude** [comment]
Yup. works correctly.
 **tcl-tls libs** are needed in order to work correctly.

**Comment by PatriotM** [comment]
good work thank you :)

**Comment by Skeddie** [comment]
Added with latest commit, thanks for your effort.
