### ISSUE TITLE
flac metadata

### ISSUE THREAD

**Issue by CptSl0w** [pzs-ng/pzs-ng#52]
hi
cant get any info from flac rels. mp3 works fine. any idea what im missing?
mp3 - [site] - ( 39M 3F - COMPLETE - House 2020 ) - [site]
(14:32:18) [2] 226- .-== PZS-NG Zipscript-C ==-------------------------.
(14:32:18) [2] 226- | + CRC-Check: oK!                                 |
(14:32:18) [2] 226- +-=[ID3tag]=------------------------===------------+
(14:32:18) [2] 226- | Genre  : House                                   |
(14:32:18) [2] 226- | Year   : 2020                                    |
(14:32:18) [2] 226- +-=[UserTop]=-------------------===----------------+

flac - [site] - ( 92M 4F - COMPLETE - Unknown 0000 ) - [site]
(14:33:20) [2] 226- .-== PZS-NG Zipscript-C ==-------------------------.
(14:33:20) [2] 226- | + CRC-Check: oK!                                 |
(14:33:20) [2] 226- +-=[ID3tag]=------------------------===------------+
(14:33:20) [2] 226- | Genre  : Unknown                                 |
(14:33:20) [2] 226- | Year   : 0000                                    |
(14:33:20) [2] 226- +-=[UserTop]=-------------------===----------------+

xxxxxxxxxxx - git-dl - multimedia.c: get_mpeg_audio_info() - values: id3_genre: Techno
this multimedia.c line dont show in debug on flac

**Comment by teqnodude** [comment]
Have you installed libflac-dev? If not then do apt install libflac-dev and recompile pzs-ng.

**Comment by PatriotM** [comment]
try

apt-get install libflac-dev

/glftpd/libcopy.sh /glftpd

make distclean; ./configure --with-glpath=/glftpd --enable-flac && make install

**Comment by CptSl0w** [comment]
have libflac
tried the steps you suggested and now i get:
(15:42:51) [2] 226- /bin/zipscript-c: error while loading shared libraries: libFLAC.so.8: cannot open shared object file: No such file or directory
(15:42:51) [2] 226- Error: post_check script (zipscript) could not be executed, file not tested.

**Comment by teqnodude** [comment]
Self explanatory, libFLAC.so.8 is missing in glftpd/lib dir. Run libcopy.sh, that should solve the problem.

**Comment by CptSl0w** [comment]
thnx you very much. solved it :)
